# Generated by Django 2.1.2 on 2018-10-13 13:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181013_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 13, 13, 19, 12, 412376, tzinfo=utc)),
        ),
    ]
